### ISSUE TITLE
UDP payload does not contain credentials

### ISSUE THREAD

**Issue by deanylev** [iharosi/ps5-wake#2]
Sorry if this is a bit of a noob question but I followed your `tcpdump` example as well as trying Wireshark, and neither of my UDP payloads contain the credentials, they just looks like this:

```
ÿÿÿÿÿÿø@NE[6@ÉÀ¨VìÀ¨Vÿ$W$VGÿSRCH * HTTP/1.1
device-discovery-protocol-version:00030010
```

**Comment by bryeartem** [comment]
Are you using tcpdump directly from your router/gateway?  I had trouble finding it myself, had to keep connecting from my laptop with remote play, and I had to only filter port 9302 to finally find it... (do not filter by IP) I'll be honest it probably took me about 5 or 6 tries to actually find the correct packet

**Comment by iharosi** [comment]
I was using on my Macbook while I was trying to wake my PS5 with the PS Remote Play mac app. Both the tcpdump and Wireshark was working for me.

**Comment by deanylev** [comment]
I'm using my MacBook Pro and filtering by port 9302, only two UDP packets appear in the list and they both contain this.

However I was trying with the Remote Play iOS app, I'll try with the Mac app.

**Comment by deanylev** [comment]
Yep, using the Mac app was the trick!

**Comment by iharosi** [comment]
Awesome!

**Comment by jonathanbower** [comment]
Is everyone here using the OSX application? I have the same original issue. I'm getting:

    22:53:21.368006 IP 10.10.1.40.9303 > 10.10.1.255.9302: UDP, length 63
        0x0000:  4500 005b 94e6 0000 8011 8e71 0a0a 0128  E..[.......q...(
        0x0010:  0a0a 01ff 2457 2456 0047 170b 5352 4348  ....$W$V.G..SRCH
        0x0020:  202a 2048 5454 502f 312e 310d 0a64 6576  .*.HTTP/1.1..dev
        0x0030:  6963 652d 6469 7363 6f76 6572 792d 7072  ice-discovery-pr
        0x0040:  6f74 6f63 6f6c 2d76 6572 7369 6f6e 3a30  otocol-version:0
        0x0050:  3030 3330 3031 300d 0a0d 0a              0030010....

I've tried both from Windows 10 and Android with the same results.

**Comment by hgregorian** [comment]
After trying numerous times using iOS app, Mac app, tcpdump on gateway, Wireshark and ettercap on Mac, I'm seeing the same packet that does not container 'user-credential'.  Did some software update to remote play axe this after the method for discovery was documented?

**Comment by iharosi** [comment]
What @jonathanbower pasted is the SRCH (search) packet, you guys need to look for the WAKEUP packet.
You need to wake your PS5 with PS Remote App and >>on the same computer<< listen for the packet with tcpdump (or wireshark etc.).

**Comment by hgregorian** [comment]
That's what I've been doing, EXCEPT the waking part (I was just connecting while it was already "awake").  I'll try again while the PS5 is in rest/standby and report back.

> What @jonathanbower pasted is the SRCH (search) packet, you guys need to look for the WAKEUP packet.
> You need to wake your PS5 with PS Remote App and >>on the same computer<< listen for the packet with tcpdump (or wireshark etc.).
