### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by rfroom** [iharosi/ps5-wake#3]
I am most likely doing something wrong, but when I compile this, I get the following errors.

[root@87176623431c ps5-wake]# gcc -o ps5-wake ps5-wake.c
/tmp/ccUk0efp.o: In function `json_output':
ps5-wake.c:(.text+0x6d2): undefined reference to `sha1_init'
ps5-wake.c:(.text+0x6ff): undefined reference to `sha1_write'
ps5-wake.c:(.text+0x70e): undefined reference to `sha1_result'
collect2: error: ld returned 1 exit status

**Comment by iharosi** [comment]
use `make` instead of `gcc`
