### ISSUE TITLE
running_app_title_id, running_app_name not populating

### ISSUE THREAD

**Issue by bryeartem** [iharosi/ps5-wake#4]
This may just be something that doesn't work but was hoping because the fields were there it would show the title.  Any chance this can be fixed or is it just not functional?

**Comment by iharosi** [comment]
Could be a leftover from the previus version of this code. I'll take a look later but this is not my priority now.

**Comment by snipem** [comment]
It is always showing "Home Screen" which is the error path.

**Comment by snipem** [comment]
There seems to be no application name and id to be stored in the response:

I outputted the payload of the ddp call:

```
Scanninghost-id : 78C8819B5B8D
host-type : PS5
host-name : PS5
host-request-port : 997
device-discovery-protocol-version : 00030010
system-version : 08050001
```

That is all.

**Comment by iharosi** [comment]
Exactly! I think, these two entries are just a left over from the old code.
