### ISSUE TITLE
Status of running app not displayed correctly

### ISSUE THREAD

**Issue by d4kine** [iharosi/ps5-wake#6]
I didn't receive the correct status when I send a proper request via `./ps5-wake -vP -j -H 10.1.1.10 |jq`. The running app won't be fetched and only "Home Screen" is displayed as a found device, even if I start any games. Tested with Astro's Playroom and Cyberpunk 2077 - both results in the same output.

General output:
```bash
Device found: PS5 [PS5/XXXXXXXXXXXX]: Home Screen
```
JSON output:
```json
{
  "code": 200,
  "host_id": "XXXXXXXXXXXXXXXX",
  "host_name": "PS5",
  "host_type": "PS5",
  "running_app_name": null,
  "running_app_titleid": null,
  "version": null,
  "host_request_port": 997,
  "timestamp": 1610804748,
  "fingerprint": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}
```

Thanks :)

**Comment by iharosi** [comment]
Thanks @d4kine!

Looks like PS5 is not sending this piece of information now unfortunately.
