### ISSUE TITLE
Any hints on sniffing the user credentials?

### ISSUE THREAD

**Issue by vmx-kbabenko** [iharosi/ps5-wake#9]
Hola, 

I've been trying to sniff those user creds while waking up PS5 from the remote app. 
On the port 9302 in particular I see only "device-discovery-protocol-version" messages a few times during boot.
Setting a wider filter (broadcast and host addresses) and I still don't see anything remotely resembling those user credentials. Did they change the behaviour? Or I am looking at it wrong?
Thanks.

**Comment by DrzalekM** [comment]
Maybe hint..
try diferent connection.. When I have Linux on Wifi it only shows device-discovery-protocol-version .. then I put both device on LAN and credentials popup in first try ..

**Comment by vmx-kbabenko** [comment]
Gotcha, I will try that. Thanks.

BTW, what's the format of those credentials? Is it like 6-7 digits? Or is it something more complex? 
If it's just digits, I could juts bruteforce it in reasonable time.

**Comment by DrzalekM** [comment]
looks like this ->
![cred](https://user-images.githubusercontent.com/78076916/109489402-1bc4fb80-7a87-11eb-98dc-c374459f6e7a.png)
Credential is number placed where is white blank space on image

**Comment by vmx-kbabenko** [comment]
I mean, is this a sequence of numbers or is it a random string?

**Comment by vmx-kbabenko** [comment]
Finally I have been able to sniff it. Connected over the Wifi and doing tcpdump on the Wifi access point (authentication was local, not coming from outside). 
Now I can finally substitute crappy CEC implementation with homebridge. 

Thank for the suggestions @DrzalekM!

**Comment by esabol** [comment]
On your PS5, if you go into Settings -> System -> Remote Play and select Link Device, it gives you an 8-digit number. Is that the same as the “user credential”? Or is it related? Just wondering if that might be an easier way than using tcpdump....

**Comment by ThomasPrior** [comment]
> On your PS5, if you go into Settings -> System -> Remote Play and select Link Device, it gives you an 8-digit number. Is that the same as the “user credential”? Or is it related? Just wondering if that might be an easier way than using tcpdump....

The passcode on that screen is not the same as the credential sniffed.

**Comment by mreassassin** [comment]
I'm not seeing any WAKE HTTP in my sniff...  I only see M-SEARCH HTTP  but those don't seem to carry any credentials.  I've tried over wifi and LAN.  no luck so far.  any ideas?

**Comment by esabol** [comment]
> I'm not seeing any WAKE HTTP in my sniff... I only see M-SEARCH HTTP but those don't seem to carry any credentials. I've tried over wifi and LAN. no luck so far. any ideas?

Are you using an iPhone/iPad (which I will henceforth refer to as an iDevice)? If so, the same thing happened to me. Here’s what I did, and it worked for me:

1. First, you need to connect your iDevice to your Mac using a USB cable. Keep it connected that way until done.
2. Then, you need to get your iDevice’s UDID somehow. If you still have iTunes, you can click on your device’s Serial Number there and then right-click or control-click on the UDID to copy it. There is probably something similar in the Finder’s iPhone/iPad interface on more recent macOS releases, but I don’t know about that.
3. Open the Terminal window and execute the following command: `rvictl -s <UDID>`
where `<UDID>` is the value from step 2.
If that command isn’t found, you might need to install XCode or XCode Command Line Tools.
If that command doesn’t respond with a message that says something like `Starting device <UDID> [SUCCEEDED] with interface rvi0`, then you have a problem somewhere. You might need to do something in XCode or iTunes to get the iDevice to trust your Mac. Not sure.
4. `sudo tcpdump -s0 -X -n -i rvi0 udp and port 9302`
5. Connect to your PS5 using PS Remote Play app on your tethered iDevice and watch the output captured by tcpdump in Terminal. You should see your user credential now, I hope.
6. Hit control-C to quit tcpdump.
7. `rvictl -x <UDID>`
Done. Hope this helps!

**Comment by vmx-kbabenko** [comment]
> I'm not seeing any WAKE HTTP in my sniff... I only see M-SEARCH HTTP but those don't seem to carry any credentials. I've tried over wifi and LAN. no luck so far. any ideas?

Just keep trying. Alternate between wifi and cable. At some point they will show up. Not sure when/where they are being cached and how long it takes to find them. In my case I've been sniffing them for 2 days. I've also been using "PS Remote Play" on Mac. 
What I can tell you, when I've finally got those credentials, I've seen them on the wifi dish, not on the router (I have separate wifi device, it's not on router), meaning that was a local communication, so make sure you tcpdump from the right place.

**Comment by Janky0** [comment]
I'm going to hang on here. I'm trying to sniff this out via my Raspberry with:

` sudo tcpdump -s0 -X -n -i eth0 host 192.168.178.70 and udp and port 9302 -v`

But no output comes. What is wrong here?

**Comment by suibari** [comment]
@Janky0 

I also tried to sniff by the raspberry pi but failed.
In conclusion, as iharosi stated in issues#2, I think impossible to it.
because the PC for WoL and the PC for Remote Play must be the same.

> What @jonathanbower pasted is the SRCH (search) packet, you guys need to look for the WAKEUP packet.
You need to wake your PS5 with PS Remote App and >>on the same computer<< listen for the packet with tcpdump (or wireshark etc.).

I gave up on the raspberry pi and was able to listen for credentials by running Wireshark on a windows PC and then running remote play on that PC.
I hope it works for you.

**Comment by Tofandel** [comment]
Does your PS5 actually need to be found on the network for the sniff to work? I have remote play already enabled and wireshark listening, I keep starting the connection but I'm outside the network of the PS5, but I don't see any of the packets with user-credentials
